// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: predict.proto

package com.microservice.k8sclient.grpc;

public interface historyReqOrBuilder extends
    // @@protoc_insertion_point(interface_extends:historyReq)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .historyStruct data = 1;</code>
   */
  java.util.List<com.microservice.k8sclient.grpc.historyStruct> 
      getDataList();
  /**
   * <code>repeated .historyStruct data = 1;</code>
   */
  com.microservice.k8sclient.grpc.historyStruct getData(int index);
  /**
   * <code>repeated .historyStruct data = 1;</code>
   */
  int getDataCount();
  /**
   * <code>repeated .historyStruct data = 1;</code>
   */
  java.util.List<? extends com.microservice.k8sclient.grpc.historyStructOrBuilder> 
      getDataOrBuilderList();
  /**
   * <code>repeated .historyStruct data = 1;</code>
   */
  com.microservice.k8sclient.grpc.historyStructOrBuilder getDataOrBuilder(
      int index);
}
