// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: predict.proto

package com.microservice.k8sclient.grpc;

public interface historyStructOrBuilder extends
    // @@protoc_insertion_point(interface_extends:historyStruct)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>double timestamp = 1;</code>
   */
  double getTimestamp();

  /**
   * <code>double value = 2;</code>
   */
  double getValue();
}
