// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: predict.proto

package com.microservice.k8sclient.grpc;

/**
 * Protobuf type {@code predictResp}
 */
public  final class predictResp extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:predictResp)
    predictRespOrBuilder {
private static final long serialVersionUID = 0L;
  // Use predictResp.newBuilder() to construct.
  private predictResp(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private predictResp() {
    result_ = emptyDoubleList();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private predictResp(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 9: {
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              result_ = newDoubleList();
              mutable_bitField0_ |= 0x00000001;
            }
            result_.addDouble(input.readDouble());
            break;
          }
          case 10: {
            int length = input.readRawVarint32();
            int limit = input.pushLimit(length);
            if (!((mutable_bitField0_ & 0x00000001) != 0) && input.getBytesUntilLimit() > 0) {
              result_ = newDoubleList();
              mutable_bitField0_ |= 0x00000001;
            }
            while (input.getBytesUntilLimit() > 0) {
              result_.addDouble(input.readDouble());
            }
            input.popLimit(limit);
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) != 0)) {
        result_.makeImmutable(); // C
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.microservice.k8sclient.grpc.PredictResourceProto.internal_static_predictResp_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.microservice.k8sclient.grpc.PredictResourceProto.internal_static_predictResp_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.microservice.k8sclient.grpc.predictResp.class, com.microservice.k8sclient.grpc.predictResp.Builder.class);
  }

  public static final int RESULT_FIELD_NUMBER = 1;
  private com.google.protobuf.Internal.DoubleList result_;
  /**
   * <code>repeated double result = 1;</code>
   */
  public java.util.List<java.lang.Double>
      getResultList() {
    return result_;
  }
  /**
   * <code>repeated double result = 1;</code>
   */
  public int getResultCount() {
    return result_.size();
  }
  /**
   * <code>repeated double result = 1;</code>
   */
  public double getResult(int index) {
    return result_.getDouble(index);
  }
  private int resultMemoizedSerializedSize = -1;

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    getSerializedSize();
    if (getResultList().size() > 0) {
      output.writeUInt32NoTag(10);
      output.writeUInt32NoTag(resultMemoizedSerializedSize);
    }
    for (int i = 0; i < result_.size(); i++) {
      output.writeDoubleNoTag(result_.getDouble(i));
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    {
      int dataSize = 0;
      dataSize = 8 * getResultList().size();
      size += dataSize;
      if (!getResultList().isEmpty()) {
        size += 1;
        size += com.google.protobuf.CodedOutputStream
            .computeInt32SizeNoTag(dataSize);
      }
      resultMemoizedSerializedSize = dataSize;
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.microservice.k8sclient.grpc.predictResp)) {
      return super.equals(obj);
    }
    com.microservice.k8sclient.grpc.predictResp other = (com.microservice.k8sclient.grpc.predictResp) obj;

    if (!getResultList()
        .equals(other.getResultList())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getResultCount() > 0) {
      hash = (37 * hash) + RESULT_FIELD_NUMBER;
      hash = (53 * hash) + getResultList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.microservice.k8sclient.grpc.predictResp parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.microservice.k8sclient.grpc.predictResp parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.microservice.k8sclient.grpc.predictResp parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.microservice.k8sclient.grpc.predictResp parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.microservice.k8sclient.grpc.predictResp parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.microservice.k8sclient.grpc.predictResp parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.microservice.k8sclient.grpc.predictResp parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.microservice.k8sclient.grpc.predictResp parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.microservice.k8sclient.grpc.predictResp parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.microservice.k8sclient.grpc.predictResp parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.microservice.k8sclient.grpc.predictResp parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.microservice.k8sclient.grpc.predictResp parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.microservice.k8sclient.grpc.predictResp prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code predictResp}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:predictResp)
      com.microservice.k8sclient.grpc.predictRespOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.microservice.k8sclient.grpc.PredictResourceProto.internal_static_predictResp_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.microservice.k8sclient.grpc.PredictResourceProto.internal_static_predictResp_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.microservice.k8sclient.grpc.predictResp.class, com.microservice.k8sclient.grpc.predictResp.Builder.class);
    }

    // Construct using com.microservice.k8sclient.grpc.predictResp.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      result_ = emptyDoubleList();
      bitField0_ = (bitField0_ & ~0x00000001);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.microservice.k8sclient.grpc.PredictResourceProto.internal_static_predictResp_descriptor;
    }

    @java.lang.Override
    public com.microservice.k8sclient.grpc.predictResp getDefaultInstanceForType() {
      return com.microservice.k8sclient.grpc.predictResp.getDefaultInstance();
    }

    @java.lang.Override
    public com.microservice.k8sclient.grpc.predictResp build() {
      com.microservice.k8sclient.grpc.predictResp result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.microservice.k8sclient.grpc.predictResp buildPartial() {
      com.microservice.k8sclient.grpc.predictResp result = new com.microservice.k8sclient.grpc.predictResp(this);
      int from_bitField0_ = bitField0_;
      if (((bitField0_ & 0x00000001) != 0)) {
        result_.makeImmutable();
        bitField0_ = (bitField0_ & ~0x00000001);
      }
      result.result_ = result_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.microservice.k8sclient.grpc.predictResp) {
        return mergeFrom((com.microservice.k8sclient.grpc.predictResp)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.microservice.k8sclient.grpc.predictResp other) {
      if (other == com.microservice.k8sclient.grpc.predictResp.getDefaultInstance()) return this;
      if (!other.result_.isEmpty()) {
        if (result_.isEmpty()) {
          result_ = other.result_;
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          ensureResultIsMutable();
          result_.addAll(other.result_);
        }
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.microservice.k8sclient.grpc.predictResp parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.microservice.k8sclient.grpc.predictResp) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private com.google.protobuf.Internal.DoubleList result_ = emptyDoubleList();
    private void ensureResultIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        result_ = mutableCopy(result_);
        bitField0_ |= 0x00000001;
       }
    }
    /**
     * <code>repeated double result = 1;</code>
     */
    public java.util.List<java.lang.Double>
        getResultList() {
      return ((bitField0_ & 0x00000001) != 0) ?
               java.util.Collections.unmodifiableList(result_) : result_;
    }
    /**
     * <code>repeated double result = 1;</code>
     */
    public int getResultCount() {
      return result_.size();
    }
    /**
     * <code>repeated double result = 1;</code>
     */
    public double getResult(int index) {
      return result_.getDouble(index);
    }
    /**
     * <code>repeated double result = 1;</code>
     */
    public Builder setResult(
        int index, double value) {
      ensureResultIsMutable();
      result_.setDouble(index, value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated double result = 1;</code>
     */
    public Builder addResult(double value) {
      ensureResultIsMutable();
      result_.addDouble(value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated double result = 1;</code>
     */
    public Builder addAllResult(
        java.lang.Iterable<? extends java.lang.Double> values) {
      ensureResultIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, result_);
      onChanged();
      return this;
    }
    /**
     * <code>repeated double result = 1;</code>
     */
    public Builder clearResult() {
      result_ = emptyDoubleList();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:predictResp)
  }

  // @@protoc_insertion_point(class_scope:predictResp)
  private static final com.microservice.k8sclient.grpc.predictResp DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.microservice.k8sclient.grpc.predictResp();
  }

  public static com.microservice.k8sclient.grpc.predictResp getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<predictResp>
      PARSER = new com.google.protobuf.AbstractParser<predictResp>() {
    @java.lang.Override
    public predictResp parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new predictResp(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<predictResp> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<predictResp> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.microservice.k8sclient.grpc.predictResp getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

