// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: predict.proto

package com.microservice.k8sclient.grpc;

public interface predictRespOrBuilder extends
    // @@protoc_insertion_point(interface_extends:predictResp)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated double result = 1;</code>
   */
  java.util.List<java.lang.Double> getResultList();
  /**
   * <code>repeated double result = 1;</code>
   */
  int getResultCount();
  /**
   * <code>repeated double result = 1;</code>
   */
  double getResult(int index);
}
